# Generated by Django 5.1.1 on 2024-09-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_bookpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
