# Generated by Django 5.1.1 on 2024-09-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpost',
            name='author',
            field=models.CharField(default='N/A', max_length=300),
        ),
        migrations.AddField(
            model_name='bookpost',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='bookpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
