# Generated by Django 5.1.1 on 2024-09-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_bookpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpost',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
