# Generated by Django 5.1.1 on 2024-09-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_bookpost_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpost',
            name='publish_date',
        ),
    ]
