# Generated by Django 5.1.1 on 2024-09-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_remove_bookpost_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Reserved')], default=0),
        ),
    ]
