# Generated by Django 5.1.1 on 2024-09-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_bookpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Reserved'), (2, 'Saved')], default=0),
        ),
    ]
