# Generated by Django 5.1.1 on 2024-09-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_reservedbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookpost',
            options={'ordering': ['-status']},
        ),
        migrations.DeleteModel(
            name='ReservedBook',
        ),
    ]
