# Generated by Django 5.1.1 on 2024-09-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_bookpost_options_delete_reservedbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookpost',
            options={},
        ),
    ]
