# Generated by Django 5.1.1 on 2024-09-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_bookpost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Saved')], default=0),
        ),
    ]
