# Generated by Django 5.1.1 on 2024-09-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_alter_bookpost_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='zip_files/')),
            ],
        ),
    ]
