# Generated by Django 5.1.1 on 2024-09-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_zipfilemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZipFileModel',
        ),
    ]
